### ISSUE TITLE
Allow Null defaults to false

### ISSUE THREAD

**Issue by sbesh91** [tkottke90/sequelize-migration-builder#1]
The allowNull function currently defaults to false.  Using the allowNull function and not passing it true is a bit pointless.  I'd suggest removing the boolean parameter all-together and just making allowNull a function that makes a column nullable without parameter.

**Comment by tkottke90** [comment]
Looking into the Postgres and MySQL I found that both at least most of the time will set a value to `NULL` unless.

> Postgres:
> If no default value is declared explicitly, the default value is the null value. This usually makes sense because a null value can be considered to represent unknown data.

> MySQL:
>  If a data type specification includes no explicit DEFAULT value, MySQL determines the default value as follows:
>
> If the column can take NULL as a value, the column is defined with an explicit DEFAULT NULL clause.
>
> If the column cannot take NULL as a value, MySQL defines the column with no explicit DEFAULT clause.

**Comment by tkottke90** [comment]
Thinking about this further, I think the right choice is to not have an opinion.  

MySQL is a good example that shows that depending on the dialect the project is using would change what including that field would mean.  It would be better to leave that up to the developer to decide if the field is `optional` or `required`.
